### ISSUE TITLE
Change nsm_mailto to operational email address

### ISSUE THREAD

**Issue by gene1wood** [nubisproject/nubis-puppet-nsm#12]
Currently emails for all nubis accounts from Bro are sent to `infosec@mozilla.com`. Please update this hiera setting, `nsm_mailto` to send to the MOC or to the operational team that administers the AWS account hosting nubis as these alerts are operational in nature. Only the moc or the ops team for the account can respond to these emails, infosec doesn't have access to do so and isn't the ops team for these nubis accounts.

**Comment by gene1wood** [comment]
@michalpurzynski Here's the ticket on these emails.

**Comment by limed** [comment]
Fix can happen here for reference https://github.com/nubisproject/nubis-nat/blob/develop/nubis/puppet/00_nat.pp#L76
